---
kind: pipeline
name: node8

steps:
    - name: test_node_8
      image: node:8
      commands:
          - yarn install
          - npx jest

    - name: test_node_10
      image: node:10
      commands:
          - yarn install
          - yarn audit --level moderate
          - npx jest

    - name: test_node_12
      image: node:12
      commands:
          - yarn install
          - yarn audit --level moderate
          - npx jest
